project_name: "DIFFUSION-COOKBOOK"
run_name: "stable-diffusion-latent"

dataset:
  name: "MNIST"
  root: "./data"
  img_size: 32
  channels: 1

vae:
  latent_dim: 4
  scaling_factor: 0.18215 

model:
  type: "latent_unet"
  base_channels: 64
  channel_mult: [1, 2]
  num_res_blocks: 2

diffusion:
  timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.0120
  schedule: "scaled_linear"

train:
  batch_size: 256
  lr: 0.001
  epochs: 10
  device: "cuda"

mlflow:
  experiment_name: "MNIST_Diffusion"
